auth_system/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from .views import HomePage,Register,Login


app_name = 'auth_system'

urlpatterns = [
    path('home/', HomePage,name="home-page"),  #what have used to connectthe apps
    path('register/',Register,name="register-page"),
    path('login/',Login,name="login-page"),


      path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='auth_system/password_reset.html',
        email_template_name='auth_system/password_reset_email.html',
        subject_template_name='auth_system/password_reset_subject.txt'
    ), name='password_reset'),

path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
    template_name='auth_system/password_reset_done.html'
), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='auth_system/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='auth_system/password_reset_complete.html'
    ), name='password_reset_complete'),
    
    ]

authentication/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_system.urls')),
    path('', include('home_page.urls')),

    
]

home_page/urls.py
from django.urls import path
from .views import MainPage,Harvestshow,Settings,Help,add_crops,show_crops,update,delete_crop,add_animals,show_animals,update_animal,delete_animal,add_machinery,show_machinery,update_machinery,delete_machinery,add_expenses,show_expenses,update_expenses,delete_expenses,add_reports,show_reports,update_reports,delete_reports,add_overview,show_overview,update_overview,delete_overview,add_employees,show_employees,update_employees,delete_employees,upload_image,display_gallery,delete_image
from home_page import views 

from django.conf import settings
from django.conf.urls.static import static

app_name='home_page'

urlpatterns = [
    # ... other URL patterns
    path('mainpage/',MainPage, name="main-page"),

    path('harvest/',Harvestshow, name="harvest"),

    #path('expenses/',Expenses,name="expenses"),

    path('settings/', Settings, name="settings"),

    path('help/',Help, name="help"),


    path('create/', add_crops, name='add-crops'),

    path('harvestshow/',show_crops, name='show-crops'),

    path('update/<int:id>/', update, name='update-crops'),
    path('delete/<int:id>/', delete_crop, name='delete-crops'),

   path('add/',add_animals,name='add-animals'),

   path('showanimals/',show_animals,name='show-animals'),

   path('update_animal/<int:id>/', update_animal, name='update-animal'),

   path('delete_annimal/<int:id>/', delete_animal, name='delete-animal'),

   path('add_machinery/', add_machinery, name='add-machinery'),
   path('show_machinery/', show_machinery, name='show-machinery'),
   path('update_machinery/<str:number_plate>/',update_machinery, name='update-machinery'),
   path('delete_machinery/<str:number_plate>/',delete_machinery,name="delete-machinery"),
   path('add_expenses/',add_expenses,name="add-expenses"),
   path('show_expenses/',show_expenses,name="show-expenses"),
   
    path('update_expenses/<int:Eid>/', update_expenses, name='update-expenses'),
    path('delete_expenses/<int:Eid>/',delete_expenses, name="delete-expenses"),


    path('add_reports/',add_reports, name='add-reports'),
    path('show_reports/', show_reports, name="show-reports"),
    path('update_reports/<int:Rid>/',update_reports, name="update-reports"),
    path('delete_reports/<int:Rid>/',delete_reports, name="delete-reports" ),


    path('add_overview/',add_overview, name="add-overview"),
    path('show_overview/', show_overview, name="show-overview"),
    path('update_overview/<int:Fid>/',update_overview, name="update-overview"),
    path('delete_overview/<int:Fid>/',delete_overview, name="delete-overview"),


    path('add_employees/',add_employees,name="add-employees"),
    path('show_employees/',show_employees, name="show-employees"),
    path('update_employees/<int:Eid>/',update_employees, name="update-employees"),
    path('delete_employees/<int:Eid>/',delete_employees,name="delete-employees"),


    path('upload_image/',upload_image, name="upload-image"),
    path('display_gallery/', display_gallery,name="display-gallery"),
    path('delete_image/<int:image_id>/',delete_image,name="delete-image")

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# makes the photo to appear

auth_system/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse

from django.shortcuts import render

from django.urls import path
from . import views

# Create your views here.
def HomePage(request):
    return render(request,'home_page/home.html', {})

def Register(request):
    if request.method =='POST':
        username=request.POST.get('username')
        last_name = request.POST.get('last_name')
        email=request.POST.get('email')
        password=request.POST.get('pwd')
        
        if User.objects.filter(username=username).exists():
            error_message = 'Username already exists. Please choose a different username.'
            return render(request, 'auth_system/register.html', {'error_message': error_message})

        new_user = User.objects.create_user(username=username,last_name=last_name,email=email,password=password)
        new_user.first_name=username
        new_user.last_name=last_name

        new_user.save()
        return redirect('auth_system:login-page')


    return render(request,'auth_system/register.html', {})

def  Login(request):
    if request.method =='POST':
        username=request.POST.get('fname')
        password=request.POST.get('pwd')
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('auth_system:home-page')   #the first home_page is for the app replace with auth_system second home_page
        else:
            return HttpResponse("error. the user does not exist")



    return render(request,'auth_system/login.html', {})


  

auth_system/templates/auth_system/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
</head>  
<body>  
<h2>Welcome to HomePage!!!</h2>   
</body>  
</html> 

auth_system/templates/auth_system/login.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>
    {%load static%}  
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
</head>  
<body>  
 <div class=container>
  <div class="thehead">
  <h3>LOGIN PAGE</h3> 
  <img src="{% static 'images/logo.png' %}" alt="Logo" width="150" height="90">
  </div>
  <form action="" method=POST>
    {% csrf_token %}
    <label for="fname">First Name</label>   
    <input type="text" placeholder="Registered Name" name='fname' required> <br>

    <label for ="fname">Password</label>
    <input type="password" placeholder="input the correct password" name='pwd' required>  <br>

    
    <input type="submit" value="Login">
    <p>forgot password? <a href="{% url 'auth_system:password_reset' %}">reset password</a></p>
  </form>
 </div>
</body>  
</html> 

auth_system/templates/auth_system/password_reset.html
  <h2>Password Reset</h2>
  <p>Enter the email address associated with your account to reset your password.</p>
  
  <form method="POST">
    {% csrf_token %}
    {{form}}

    <input type="submit" name="send email">
  </form>

auth_system/templates/auth_system/password_reset_confirm.html
<h2>Reset Password Confirmation</h2>
<p>Please enter your new password below:</p>

<form method="post">

  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit">Reset Password</button>
</form>

auth_system/templates/auth_system/password_reset_done.html
<h4>Password reseting has been successfull</h4>
<p>Your password has been reset you can go on and login again</p>

<a href="/">login-page</a>

auth_system/templates/auth_system/password_reset_email.html
{% load i18n %}
{% autoescape off %}

{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'auth_system:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

auth_system/templates/auth_system/password_reset_form.html
<h2>Password Reset</h2>
<form method="POST" action="{% url 'auth_system:password_reset' %}">
  {% csrf_token %}
  
  <label for="id_email">Email:</label>
  <input type="email" name="email" required>
  <button type="submit">Reset Password</button>
</form>

auth_system/templates/auth_system/password_reset_sent.html
<h5> Password reset sent<h5>

    <p5>Not received the email?
    Make sure the entered password is the address you registered with. Else check ths spam folder</p5>

auth_system/templates/auth_system/register.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title> 
    {%load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>  
<body>   
<div class="form"> 
    <h3>REGISTER</h3>
    <img src="{% static 'images/logo.png' %}" alt="Logo" width="150" height="90">
    {% if error_message %}
        <p class="error">{{ error_message }}</p>
    {% endif %}
    <form action="" method=POST>
        {% csrf_token %}
        <label for ="fname">First Name</label>
        <input type="text" placeholder="First Name in uppercase" name='username'required> <br>

        <label for="fname"> Last Name</label>
        <input type="text" placeholder="Last Name in uppercase" name='last_name'required> <br>

        <label for="fname">Email</label>
        <input type="email"placeholder="Valid Email" name='email'required> <br>

        <label for="fname">Password</label>
        <input type="Password" placeholder="Create a Strong Password" name='pwd'required> <br>

        <button type="submit">Submit</button> <br>

        <p>Already have an account <a href="{% url 'auth_system:login-page' %}">login</a></p>


    </form>
</div>  
</body>  
</html> 