authentication/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_system.urls')),
    path('', include('home_page.urls')),

    
]

home_page/urls.py
from django.urls import path
from .views import MainPage,Harvestshow,Settings,Help,add_crops,show_crops,update,delete_crop,add_animals,show_animals,update_animal,delete_animal,add_machinery,show_machinery,update_machinery,delete_machinery,add_expenses,show_expenses,update_expenses,delete_expenses,add_reports,show_reports,update_reports,delete_reports,add_overview,show_overview,update_overview,delete_overview,add_employees,show_employees,update_employees,delete_employees,upload_image,display_gallery,delete_image
from home_page import views 

from django.conf import settings
from django.conf.urls.static import static

app_name='home_page'

urlpatterns = [
    # ... other URL patterns
    path('mainpage/',MainPage, name="main-page"),

    path('harvest/',Harvestshow, name="harvest"),

    #path('expenses/',Expenses,name="expenses"),

    path('settings/', Settings, name="settings"),

    path('help/',Help, name="help"),


    path('create/', add_crops, name='add-crops'),

    path('harvestshow/',show_crops, name='show-crops'),

    path('update/<int:id>/', update, name='update-crops'),
    path('delete/<int:id>/', delete_crop, name='delete-crops'),

   path('add/',add_animals,name='add-animals'),

   path('showanimals/',show_animals,name='show-animals'),

   path('update_animal/<int:id>/', update_animal, name='update-animal'),

   path('delete_annimal/<int:id>/', delete_animal, name='delete-animal'),

   path('add_machinery/', add_machinery, name='add-machinery'),
   path('show_machinery/', show_machinery, name='show-machinery'),
   path('update_machinery/<str:number_plate>/',update_machinery, name='update-machinery'),
   path('delete_machinery/<str:number_plate>/',delete_machinery,name="delete-machinery"),
   path('add_expenses/',add_expenses,name="add-expenses"),
   path('show_expenses/',show_expenses,name="show-expenses"),
   
    path('update_expenses/<int:Eid>/', update_expenses, name='update-expenses'),
    path('delete_expenses/<int:Eid>/',delete_expenses, name="delete-expenses"),


    path('add_reports/',add_reports, name='add-reports'),
    path('show_reports/', show_reports, name="show-reports"),
    path('update_reports/<int:Rid>/',update_reports, name="update-reports"),
    path('delete_reports/<int:Rid>/',delete_reports, name="delete-reports" ),


    path('add_overview/',add_overview, name="add-overview"),
    path('show_overview/', show_overview, name="show-overview"),
    path('update_overview/<int:Fid>/',update_overview, name="update-overview"),
    path('delete_overview/<int:Fid>/',delete_overview, name="delete-overview"),


    path('add_employees/',add_employees,name="add-employees"),
    path('show_employees/',show_employees, name="show-employees"),
    path('update_employees/<int:Eid>/',update_employees, name="update-employees"),
    path('delete_employees/<int:Eid>/',delete_employees,name="delete-employees"),


    path('upload_image/',upload_image, name="upload-image"),
    path('display_gallery/', display_gallery,name="display-gallery"),
    path('delete_image/<int:image_id>/',delete_image,name="delete-image")

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# makes the photo to appear

home_page/models.py
from django.db import models

from django.contrib.auth.models import User


class Crops(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)

    cid=models.CharField(max_length=20,default=1)
    name=models.CharField(max_length=20)
    variety=models.CharField(max_length=20)
    planting_date=models.DateField()
    description=models.TextField()
    quantity=models.IntegerField()
    is_harvested=models.BooleanField(default=False)

    class Meta:
        db_table="crops"


# Animals model

class Animals(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)

    Aid=models.CharField(max_length=1000000, default=0)
    picture=models.ImageField(upload_to='animal_pictures')
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    production=models.DecimalField(decimal_places=2, max_digits=3)




    #Machinery model

class Machinery(models.Model):
        
        user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)       
        
        number_plate=models.CharField(max_length=20, primary_key=True)
        model=models.CharField(max_length=20)
        purchase_date=models.DateField()
        description=models.TextField()
        manufacture_year=models.IntegerField()
        purchase_price=models.DecimalField(decimal_places=2, max_digits=30)

        class Meta:
            db_table="machinery"


            #expense model

class Expenses(models.Model):

     user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
     
     Eid=models.IntegerField(default=1,primary_key=True)
     date=models.DateField()
     description=models.TextField()
     amount=models.BigIntegerField()
     receipt = models.FileField(upload_to='expenses/', blank=True, null=True)

     class Meta:
          db_table="expense"

          #reports model



class Reports(models.Model):

     user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
     
     Rid=models.IntegerField(default=1,primary_key=True)
     date=models.DateField()
     the_field=models.TextField()
     the_report=models.TextField()
     
class Overview(models.Model):

     user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
     
     Fid=models.IntegerField(default=1,primary_key=True)
     Assets=models.CharField(max_length=100000)
     Number=models.TextField()

     class Meta:
          db_table="farm_overview"


class Employees(models.Model):

     user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)


     Eid=models.IntegerField(default=1,primary_key=True)
     Name=models.CharField(max_length=20)
     Position=models.CharField(max_length=20)
     Salary=models.IntegerField()
     Performance=models.CharField(max_length=20)


     class Meta:
          db_table="emloyees"


class Farmimage(models.Model):

     user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
     image=models.ImageField(upload_to='farm_gallery')
     caption=models.CharField(max_length=100)
     uploaded_at = models.DateTimeField(auto_now_add=True)

home_page/views.py
from django.shortcuts import render


def MainPage(request):
    # Your view logic goes here
    return render(request,'home_page/home.html')

def Harvestshow(request):
    # Your view logic goes here
    return render(request,'home_page/harvestshow.html')

#def Expenses(request):
    # Your view logic goes here
    #return render(request,'home_page/expenses.html')

#def Reports(request):
    # Your view logic goes here
    #return render(request,'home_page/reports.html')

def Settings(request):
    # Your view logic goes here
    return render(request,'home_page/settings.html')

def Help(request):
    # Your view logic goes here
    return render(request,'home_page/help.html')

    
#view functions of cropsforms
from django.shortcuts import render,redirect
from .cropsforms import CropsForm
from .models import Crops


from django.contrib.auth.decorators import login_required



def add_crops(request):
    if request.method == 'POST':
        form = CropsForm(request.POST)
        if form.is_valid():

            crop = form.save(commit=False)
            crop.user = request.user

            form.save()
            return redirect('home_page:show-crops')
    else:
        form = CropsForm()
    
    return render(request, 'home_page/addcrops.html', {'form': form})

def show_crops(request):
    crops = Crops.objects.filter(user=request.user)
    
    return render(request,"home_page/harvestshow.html",{'crops':crops})
    
#def edit(request,id):
   # crops=Crops.objects.get(id=id)
    #return render(request,"home_page/edit.html",{'crops':crops})

def update(request,id):
    crops=Crops.objects.get(id=id)
    form=CropsForm(request.POST,instance=crops)

    if form.is_valid():
        form.save()
        return redirect("home_page:show-crops")
    return render(request,"home_page/update.html",{'crops':crops})

def delete_crop(request, id):
    crop = Crops.objects.get(id=id)

    if request.method == 'POST':
        crop.delete()
        return redirect('home_page:show-crops')

    return render(request, 'home_page/delete_crop.html', {'crop': crop})



#view function of the Animal AnimalsForm
from .animals_form import AnimalsForm
from .models import Animals

def add_animals(request):
    if request.method == 'POST':
        form = AnimalsForm(request.POST, request.FILES)
        if form.is_valid():

            animal = form.save(commit=False)
            animal.user = request.user
        

            form.save()
            return redirect('home_page:show-animals')
    else:
        form = AnimalsForm()

    return render(request, 'home_page/addanimals.html', {'form': form})

def show_animals(request):
    animals = Animals.objects.filter(user=request.user)

    return render (request,"home_page/showlivestock.html",{'animals':animals})

def update_animal(request, id):
    animals = Animals.objects.get(id=id)
    form = AnimalsForm(request.POST, instance=animals)

    if form.is_valid():
        form.save()
        return redirect("home_page:show-animals")
    return render(request, "home_page/update_animal.html", {'animals': animals})

def delete_animal(request,id):
    animal=Animals.objects.get(id=id)

    if request.method=='POST':
        animal.delete()
        return redirect('home_page:show-animals')
    
    return render(request, 'home_page/delete_animal.html',{'animal':animal})

        #view function of the Machinery MachineryForm
from .machinery_form import MachineryForm
from .models import Machinery

def add_machinery(request):
    if request.method == 'POST':
        form = MachineryForm(request.POST)
        if form.is_valid():


            machinery = form.save(commit=False)
            machinery.user = request.user
        

            form.save()
            return redirect('home_page:show-machinery')
    else:
        form = MachineryForm()

    return render(request, 'home_page/addmachinery.html', {'form': form})

def show_machinery(request):
    machinery = Machinery.objects.filter(user=request.user)

    return render (request,"home_page/showmachinery.html",{'machinery':machinery})

def update_machinery(request,number_plate):
     machinery=Machinery.objects.get(number_plate=number_plate)
     form=MachineryForm(request.POST,instance=machinery)
     
     if form.is_valid():
         form.save()
         return redirect("home_page:show-machinery")
     return render(request, "home_page/update_machinery.html", {'machinery': machinery})

def delete_machinery(request,number_plate):
    machinery=Machinery.objects.get(number_plate=number_plate)
    if request.method=='POST':
        machinery.delete()
        return redirect('home_page:show-machinery')
    return render(request,'home_page/delete_machinery.html',{'machinery':machinery})




#view function of the expenses
from .expenses_form import ExpensesForm
from .models import Expenses

def add_expenses(request):
    if request.method == 'POST':
        form = ExpensesForm(request.POST, request.FILES)
        if form.is_valid():


            expenses = form.save(commit=False)
            expenses.user = request.user
        

            form.save()
            return redirect('home_page:show-expenses')
    else:
        form = ExpensesForm()
    
    return render(request, 'home_page/add_expense.html', {'form': form})


def show_expenses(request):
    expenses = Expenses.objects.filter(user=request.user)

    return render(request,"home_page/show_expenses.html",{'expenses':expenses})


def update_expenses(request,Eid):
    expenses=Expenses.objects.get(Eid=Eid)
    form=ExpensesForm(request.POST,instance=expenses)

    if form.is_valid():
        form.save()
        return redirect("home_page:show-expenses")
    return render(request,"home_page/update_expenses.html",{'expenses':expenses})

def delete_expenses(request,Eid):
    expenses=Expenses.objects.get(Eid=Eid)
    if request.method=='POST':
        expenses.delete()
        return redirect("home_page:show-expenses")
    return render(request,'home_page/delete_expense.html',{'expenses':expenses})


#Reports view

from .reports_form import ReportsForm
from .models import Reports

def add_reports(request):
    if request.method=='POST':
        form=ReportsForm(request.POST,request.FILES)
        if form.is_valid():

            reports = form.save(commit=False)
            reports.user = request.user
        

            form.save()
            return redirect('home_page:show-reports')
    else:
        form=ReportsForm()

    return render(request,'home_page/add_report.html',{'form':form})

def show_reports(request):
    reports = Reports.objects.filter(user=request.user)

    return render(request,"home_page/show_report.html",{'reports':reports})

def update_reports(request,Rid):
    reports=Reports.objects.get(Rid=Rid)
    form=ReportsForm(request.POST,instance=reports)

    if form.is_valid():
        form.save()
        return redirect("home_page:show-reports")
    return render (request,"home_Page/update_reports.html",{'reports':reports})


def delete_reports(request,Rid):
    reports=Reports.objects.get(Rid=Rid)
    if request.method=='POST':
        reports.delete()
        return redirect("home_page:show-reports")
    return render (request,'home_page/delete_report.html',{'reports':reports})

    

    #view function of the Farm Overview
from .overview_form import OverviewForm
from .models import Overview


def add_overview(request):
    if request.method=='POST':
        form=OverviewForm(request.POST,request.FILES)
        if form.is_valid():

            overview = form.save(commit=False)
            overview.user = request.user
        

            form.save()
            return redirect('home_page:show-overview')
    else:
        form=OverviewForm()

    return render(request,'home_page/add_overview.html',{'form':form})


def show_overview(request):
    overview = Overview.objects.filter(user=request.user)
    return render(request,"home_page/show_overview.html",{'overview':Overview})


def update_overview(request,Fid):
    overview=Overview.objects.get(Fid=Fid)
    form=OverviewForm(request.POST,instance=overview)

    if form.is_valid():
        form.save()
        return redirect("home_page:show-overview")
    return render (request,"home_page/update_overview.html",{'overview':Overview})
    

def delete_overview(request, Fid):
    overview = Overview.objects.get(Fid=Fid)
    if request.method == 'POST':
        overview.delete()
        return redirect('home_page:show-overview')
    return render(request, 'home_page/delete_overview.html', {'overview': overview})



        #view function of the Employees

from .employees_form import EmployeesForm
from. models import Employees

def add_employees(request):
    if request.method=='POST':
        form=EmployeesForm(request.POST)
        if form.is_valid():

            employees = form.save(commit=False)
            employees.user = request.user
        

            form.save()
            return redirect('home_page:show-employees')
    else:
        form=EmployeesForm()

    return render(request,'home_page/add_employees.html',{'form':form})

def show_employees(request):
    employees = Employees.objects.filter(user=request.user)
    return render(request,"home_page/show_employees.html",{'employees':employees})


def update_employees(request,Eid):
    employees=Employees.objects.get(Eid=Eid)
    form=EmployeesForm(request.POST,instance=employees)

    if form.is_valid():
        form.save()
        return redirect("home_page:show-employees")
    return render(request,"home_page/update_employees.html",{'employees':employees})

def delete_employees(request,Eid):
    employees=Employees.objects.get(Eid=Eid)
    if request.method=='POST':
        employees.delete()
        return redirect('home_page:show-employees')
    return render(request,'home_page/delete_employees.html',{'employees':employees})


from.farmimage_form import FarmimageForm
from .models import Farmimage


def upload_image(request):

home_page/templates/home_page/add_employees.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
    <head>
        <title>add Employee</title>
        {%load static%}  
        <link href="{% static 'css/update_machinery.css' %}" rel="stylesheet">
    </head>
    
    <body>
        
        <form method="POST" action={%url 'home_page:add-employees'%}>
            <h2>Add Employee</h2>
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="add">
        </form>
    </body>
    {%endblock%}

home_page/templates/home_page/add_expense.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
    <head>
        <title>add Expense</title>
        {%load static%}  
        <link href="{% static 'css/update_machinery.css' %}" rel="stylesheet">
    </head>
    <body>
        
        <form method="POST" action={%url 'home_page:add-expenses'%}>
            <h2>Add Expenses</h2>
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="add">
        </form>
    </body>
    {%endblock%}

home_page/templates/home_page/add_overview.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
    <head>
        <title>add asset</title>
        {%load static%}  
        <link href="{% static 'css/update_machinery.css' %}" rel="stylesheet">
    </head>
    
    <body>
        
        <form method="POST" action={%url 'home_page:add-overview'%}>
            <h2>Add Asset</h2>
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="add">
        </form>
    </body>
    {%endblock%}

home_page/templates/home_page/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Farm Management System - Dashboard</title>

  <meta http-equiv=”X-UA-Compatible” content=”IE=edge”>

  <meta name=”viewport” content=”width=device-width, initial-scale=1.0″>
  
  <link rel="stylesheet" href="{% static 'css/base.css' %}">


</head>
<body>
  <header>
    
    <h1>WELCOME TO TECH FARM</h1>
    <!-- Add any additional header elements or navigation here -->
  </header>
  {%block content%}

  {% endblock %}

  <div class="content">
    <!-- Add the main content of the dashboard here -->
    <p>Welcome to the farm manager. Here you can monitor and manage various aspects of your farm.</p>
  </div>

  <footer>
    <!-- Add any footer content or copyright information here -->
    <p>&copy; 2023 Farm Management System created by Denis Nganga. All rights reserved.</p>
  </footer>
</body>
</html>

home_page/templates/home_page/delete_crop.html
<!DOCTYPE html>
<html>
<head>
  <title>Delete Crop</title>
  {%load static%}  
  <link href="{% static 'css/delete_crop.css' %}" rel="stylesheet">
</head>
<body>
  <div class="delete-container">
    <h1>Delete Crop</h1>
    <p>Are you sure you want to delete this crop?</p>
    <form method="post">
      {% csrf_token %}
      <input class="delete-button" type="submit" value="Delete">
      <a class="cancel-link" href="{% url 'home_page:show-crops' %}">Cancel</a>
    </form>
  </div>
</body>
</html>

home_page/templates/home_page/delete_expense.html
<!DOCTYPE html>
<html>
<head>
  <title>Delete Expense</title>
  {%load static%}  
  <link href="{% static 'css/delete_expense.css' %}" rel="stylesheet">
</head>
<body>
  <div class="delete-container">
    <h1>Delete Expense</h1>
    <p>Are you sure you want to delete this Expense?</p>
    <form method="post">
      {% csrf_token %}
      <input class="delete-button" type="submit" value="Delete">
      <a class="cancel-link" href="{% url 'home_page:show-expenses' %}">Cancel</a>
    </form>
  </div>
</body>
</html>

home_page/templates/home_page/settings.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
<head>
  <title>Welcome to Our Website</title>
</head>
  <body>settings</body>
{%endblock%}

home_page/templates/home_page/show_expenses.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
<head>
    <title>Show Expenses</title>
    {%load static%}  
  <link href="{% static 'css/show_expenses.css' %}" rel="stylesheet">
</head>
<body>
    <h2>Expenses Details</h2>
    <table>
        <thead>
            <tr>
                <th>Expense id</th>
                <th>date</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Receipt</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for expense in expenses %}
            <tr>
                <td>{{ expense.Eid }}</td>
                <td>{{ expense.date }}</td>
                <td>{{ expense.description }}</td>
                <td>{{ expense.amount }}</td>
                <td>
            
                {% if expense.receipt %}
                <a href="{{ expense.receipt.url }}" target="_blank">View Receipt</a>
            {% else %}
                N/A
            {% endif %}
               </td>  
            
            
            <td><a href="{% url 'home_page:update-expenses' Eid=expense.Eid %}" class="update-link">Update</a>
                <a href="{% url 'home_page:delete-expenses' Eid=expense.Eid %}"class="delete-link">Delete</a>


            </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  <a href="{% url 'home_page:add-expenses' %}" class="add-button">Add</a>
</body>
{% endblock %}

home_page/templates/home_page/show_overview.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
<head>
    <title>Show Assets</title>
    {%load static%}  
  <link href="{% static 'css/show_overview.css' %}" rel="stylesheet">
</head>
<body>
    <h2>Farm Overview</h2>
    <table>
        <thead>
            <tr>
                <th>Fid</th>
                <th>Assets</th>
                <th>Number</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for overview in Overview %}
            <tr>
                <td>{{ overview.Fid }}</td>
                <td>{{ overview.Assets }}</td>
                <td>{{ overview.Number }}</td>


                <td>
                    <a href="{% url 'home_page:update-overview' Fid=overview.Fid %}" class="update-link">update</a>
                    <a href="{% url 'home_page:delete-overview' Fid=overview.Fid %}"class="delete-link">Delete</a>
                </td>
                


            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'home_page:add-overview' %}" class="add-button">Add</a>
</body>
{%endblock%}

home_page/templates/home_page/showmachinery.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
<html>
<head>
    <title>Show Machinery</title>
    {%load static%}  
  <link href="{% static 'css/showmachinery.css' %}" rel="stylesheet">
</head>
<body>
    <h2>Machinery Details</h2>
    <table>
        <thead>
            <tr>
                <th>Number Plate</th>
                <th>Model</th>
                <th>Purchase Date</th>
                <th>Description</th>
                <th>Manufacture Year</th>
                <th>Purchase Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for machinery in machinery %}
            <tr>
                <td>{{ machinery.number_plate }}</td>
                <td>{{ machinery.model }}</td>
                <td>{{ machinery.purchase_date }}</td>
                <td>{{ machinery.description }}</td>
                <td>{{ machinery.manufacture_year }}</td>
                <td>{{ machinery.purchase_price }}</td>  
                <td>
                <a href="{% url 'home_page:update-machinery' number_plate=machinery.number_plate %}" class="update-link">update</a>
                <a href="{% url 'home_page:delete-machinery' number_plate=machinery.number_plate %}"class="delete-link">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'home_page:add-machinery' %}" class="add-button">Add</a>
</body>
{%endblock%}

home_page/templates/home_page/update_animal.html
<head>
  <title>update crop</title>
    {%load static%}  
    <link href="{% static 'css/update.css' %}" rel="stylesheet">
  </head>
  <body>
    <h1>Update Animal</h1>
    <form method="post">
      {% csrf_token %}
  
      <label for="id_Aid">Animal ID:</label>
      <input type="text" name="Aid" id="id_Aid" value="{{animals.Aid }}" required>
  
      <label for="id_picture"></label>
      <input type="upload" name="picture" id="id_picture" value="{{ animals.picture }}" required>
  
      <label for="id_name">Name:</label>
      <input type="text" name="name" id="id_name" value="{{ animals.name }}" required>
  
      <label for="id_age">Age:</label>
      <input type="number" name="age" id="id_age" value="{{ animals.age }}" required>
  
      <label for="id_production">Production:</label>
      <input type=number name="production" id="id_production" {{ animals.production }}required>
  
     
  
      <input type="submit" value="Update">
    </form>
  </body>

home_page/templates/home_page/update_machinery.html
<head>
    <title>update crop</title>
      {%load static%}  
      <link href="{% static 'css/update_machinery.css' %}" rel="stylesheet">
    </head>
    <body>
      <h1>Update Machinery</h1>
      <form method="post">
        {% csrf_token %}
    
        <label for="id_number_plate">Number Plate:</label>
        <input type="text" name="number_plate" id="id_number_plate" value="{{machinery.number_plate }}" required>
    
        <label for="id_model">Model:</label>
        <input type="text" name="model" id="id_model" value="{{ machinery.model }}" required>
    
        <label for="id_purchase_date">Purchase Date:</label>
        <input type="date" name="purchase_date" id="id_purchase_date" value="{{ machinery.purchase_date }}" required>
    
        <label for="id_description">Description:</label>
        <input type="text" name="description" id="id_description" value="{{ machinery.description }}" required>
    
        <label for="id_manufacture_year">Manufacture Year:</label>
        <input type="number" name="manufacture_year" id="id_manufacture_year" value="{{ machinery.manufacture_year }}"required>
    
        <label for="id_purchase_price">Purchase Price:</label>
        <input type="number" name="purchase_price" id="id_purchase_price" value="{{ machinery.purchase_price }}"required>
    
    
        <input type="submit" value="Update">
      </form>
    </body>

home_page/templates/home_page/upload_image.html
{% extends 'home_page/base.html' %}

{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/help.css' %}">

{% endblock %}

{% block content %}
<head>
<head>    
<title>add picture</title>
{{ form.media }}

{%load static%}  
<link href="{% static 'css/update_machinery.css' %}" rel="stylesheet">
</head>
<body>
    
<form method="post" enctype="multipart/form-data"><!--when you want to upload fies -->
  <h1>Add Picture</h1>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>
</body>
{%endblock%}